name: C CI

on:
  push:
    branches: [ "prod" ]
  pull_request:
    branches: [ "prod" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make

  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: build container
      run: docker build -t prodos .
    - name: run
      run: docker run -d -p 1977:1977/tcp prodos
